## 循环内创建闭包所产生的一些问题

先来看使用不当的例子

```javascript
function constfuncs() {
    var funcs = [];
    for (var i = 0; i < 5; i++) {
        funcs[i] = function () {return i;}
    }
    return funcs;
}
var funcs = constfuncs();
console.log(funcs[3]());//5
```

上面这段代码创建了5个闭包, 并将他们存储到一个数组中.

- funcs[0] = function () {return i;};
- funcs[1] = function () {return i;};
- funcs[2] = function () {return i;};
- funcs[3] = function () {return i;};
- funcs[4] = function () {return i;};

这5个闭包共享一个变量i, 当constfuncs()执行时, 变量i的值是10, 

for循环也执行完了, 但f这 5 个`function(){return i;}`还没有执行(因为后面没有())

在执行`funcs[5]()`时, `function(){return i;}`才执行(此时i老早就等于5)

其实, 这个错误的例子可以简化为

```javascript
// 错误的
var funcs = [];
for (var i = 0; i < 5; i++) {
   funcs[i] = function () {return i;}
}
funcs[2]();// 5
// 更改之后还是错误
var funcs = [];
for (var i = 0; i < 5; i++) {
   var j = i;
   funcs[j] = function () {console.log(j)}
}
funcs[2]();// 4
// 更改时候再次错误
var funcs = [];
var arr = [];
for (var i = 0; i < 5; i++) {
   arr[i] = i;
   funcs[i] = function () {console.log(arr[i])}
}
funcs[2](); // undefined arr[5]没有定义
// 正确的
var funcs = [];
for (var i = 0; i < 5; i++) {
   funcs[i] = (function(){
     var j= i;
     return function () {return j;}
   }())
}
funcs[2]();
```


### 解决办法:

**第一种: 让这个函数(闭包)返回一个总是返回v的函数**

> 闭包外面在包裹一个函数, 这个函数里引用变量i, 每循环一次就被执行, 闭包则引用这个外部函数的i.


```javascript
function constfuncs() {
    var funcs = [];
    for (var i = 0; i < 5; i++) {
        funcs[i] = (function(){var j=i;return function(){return j;}}())
    }
    return funcs;
}
var funcs = constfuncs();
console.log(funcs[3]());  //3
```

**第一种: 用函数参数来保存(其实也是利用了闭包)**

```javascript
function constfuncs() {
    var funcs = [];
    for (var i = 0; i < 5; i++) {
        funcs[i] = (function(i){return function () {return i;}}(i))
    }
    return funcs;
}
var funcs = constfuncs();
```



### 优化

```javascript
function constfunc(v) {
    return function() {
        return v;
    };
}
var funcs = [];
for (var i = 0; i < 5; i++) {
    funcs[i] = constfunc(i);
}
console.log(funcs[4]()); //=>4
```

## 例子

### 计时器

> 延迟回调函数`setTimeout(function, delay);`

先来看一个错误的例子

```javascript
for (var i = 0; i < 10; ++i) {
    setTimeout(function () {console.log(i)}, 0);
}// 这样不好, 输出的结果是十个 10
```

上面这段代码会以每秒一次的频率输出五次6, 因为延迟函数的回调会在循环结束时才执行, 只有一个词法作用域

错误原因: 

6个闭包共享一个变量i

解决方法:

```javascript
// 第一种:
for(var i = 0; i<10; i++){
	setTimeout((function(i){
      return function(){console.log(i)}
    }(i)),0)
}
// 第二种:
for(var i = 0; i<10; i++){
	setTimeout((function(i){
      var j=i;return function(){console.log(j)}
    }(i)),0)
}
// 第三种:
for (let i = 0; i < 10; ++i) {
    setTimeout(function () {console.log(i)}, 0);
}
// 第四种:
for (var i = 0; i < 10; ++i) {
    (function(i){
      setTimeout(function () {console.log(i)}, 0);
    })(i)
}
```

用闭包写计时器:

```javascript
// 正计时
for(var i=1;i<=5;i++){
    (function(){
        var j=i;
        setTimeout(function(){
            console.log(j);
        },j*1000);
    })();
 }
 
 // 倒计时
 for (var i = 10; i >= 0; i--) {
    (function(i) {
        setTimeout(function timer() {
            console.log(i);
        }, (10-i)* 1000);
    })(i)
}
```
